# Generated by Django 3.1.1 on 2020-09-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanager', '0003_auto_20200916_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ['ip_address']},
        ),
    ]
