# Generated by Django 3.1.1 on 2020-09-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanager', '0004_auto_20200916_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidrblock',
            name='netmask',
            field=models.GenericIPAddressField(blank=True, default=None, null=True, protocol='IPv4'),
        ),
    ]
