# Generated by Django 3.1.1 on 2020-09-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanager', '0005_cidrblock_netmask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='cidr_block',
            new_name='cidr_block_id',
        ),
    ]
