# Generated by Django 3.1.1 on 2020-09-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanager', '0006_auto_20200917_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ['cidr_block_id', 'ip_address']},
        ),
    ]
